/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#3d0011',
        'on-primary': '#ffffff',
        'primary-container': '#630321',
        'on-primary-container': '#eb6f84',
        secondary: '#58632b',
        'on-secondary': '#ffffff',
        'secondary-container': '#d9e6a0',
        'on-secondary-container': '#5d682f',
        tertiary: '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cca72f',
        'on-tertiary-container': '#4e3d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        surface: '#faf9f7',
        'surface-bright': '#faf9f7',
        'surface-dim': '#dadad8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeec',
        'surface-container-high': '#e9e8e6',
        'surface-container-highest': '#e3e2e0',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#564244',
        outline: '#897173',
        'outline-variant': '#dcc0c2',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1ef',
        'inverse-primary': '#ffb2bb',
        'surface-tint': '#a4384e',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-gap': '120px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
